// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqhlftconhnffznriybc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxaGxmdGNvbmhuZmZ6bnJpeWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNjYzNzMsImV4cCI6MjA3ODY0MjM3M30.ut9i6-V4GWZkWhVvk3lrgzy3QT4GCAG98wS3HDCRx-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});